import assert from 'node:assert/strict';
import {normalizeMarketTick} from '../server/market-tick-contract.mjs';
const now=Date.parse('2026-10-09T12:00:00.000Z');
const valid=normalizeMarketTick({ticker:'BTC',symbol:'BTCUSDT',price:65000,changePct:1.2,volume:123,high:66000,low:64000,source:'Binance',time:new Date(now-30000).toISOString()},now);
assert.equal(valid.ok,true);
assert.equal(valid.value.ticker,'BTC');
assert.equal(valid.value.sourceVerified,false);
assert.match(valid.value.source,/client-reported.*unverified/i);
assert.match(valid.value.source,/claimed provider: Binance/i);
assert.equal(valid.value.time,new Date(now-30000).toISOString());
assert.equal(normalizeMarketTick({},now).error,'INVALID_TICKER');
assert.equal(normalizeMarketTick({ticker:'BTC',price:0},now).error,'INVALID_PRICE');
assert.equal(normalizeMarketTick({ticker:'BTC',price:Infinity},now).error,'INVALID_PRICE');
assert.equal(normalizeMarketTick({ticker:'../secret',price:1},now).error,'INVALID_TICKER');
assert.equal(normalizeMarketTick({ticker:'BTC',price:1,changePct:10001},now).error,'INVALID_CHANGE_PCT');
assert.equal(normalizeMarketTick({ticker:'BTC',price:1,volume:-1},now).error,'INVALID_VOLUME');
assert.equal(normalizeMarketTick({ticker:'BTC',price:10,high:9},now).error,'HIGH_BELOW_LAST_PRICE');
assert.equal(normalizeMarketTick({ticker:'BTC',price:10,low:11},now).error,'LOW_ABOVE_LAST_PRICE');
assert.equal(normalizeMarketTick({ticker:'BTC',price:10,low:12,high:11},now).error,'INVALID_PRICE_RANGE');
assert.equal(normalizeMarketTick({ticker:'BTC',price:10,time:'not a timestamp'},now).error,'INVALID_OBSERVED_AT');
assert.equal(normalizeMarketTick({ticker:'BTC',price:10,time:new Date(now-8*24*60*60*1000).toISOString()},now).error,'STALE_MARKET_TICK');
assert.equal(normalizeMarketTick({ticker:'BTC',price:10,time:new Date(now+6*60*1000).toISOString()},now).error,'FUTURE_MARKET_TICK');
const noSource=normalizeMarketTick({ticker:'AAPL',symbol:'AAPL',price:210},now);
assert.equal(noSource.ok,true);
assert.match(noSource.value.source,/provider not supplied/i);
assert.equal(noSource.value.changePct,null);
assert.equal(noSource.value.volume,null);
assert.equal(normalizeMarketTick([],now).error,'INVALID_PAYLOAD');
console.log('Market tick contract: invalid payloads, impossible values, timestamps and unverified provider claims covered.');
