import fs from 'node:fs';
import assert from 'node:assert/strict';

const frontend = fs.readFileSync(new URL('../public/market-data-os.js', import.meta.url), 'utf8');
const server = fs.readFileSync(new URL('../server/server.mjs', import.meta.url), 'utf8');
const nasdaqEod = fs.readFileSync(new URL('../server/nasdaq-eod.mjs', import.meta.url), 'utf8');

assert.match(frontend, /\/api\/market-data-stream\?ticker=/, 'frontend should connect to the market-data stream endpoint');
assert.doesNotMatch(frontend, /new EventSource\('\/api\/market-stream\?ticker=/, 'frontend should not use the legacy crypto-only stream');
assert.match(frontend, /d\.verified&&d\.status==='LIVE'/, 'stream data must be verified and LIVE before being shown as live');
assert.match(frontend, /x\.live===true&&x\.executionEligible===true&&String\(x\.sourceTimestampType\|\|x\.timestampType\|\|''\)\.toUpperCase\(\)==='PROVIDER_TIMESTAMP'/, 'fallback report must require explicit execution eligibility and provider timestamp provenance before LIVE status');
assert.match(frontend, /quoteAge>=-30000&&quoteAge<=90000/, 'fallback report must reject future-dated and stale quotes');
assert.match(frontend, /d\.executionEligible===true&&providerTime/, 'dashboard freshness labels must share the strict execution gate');
assert.match(frontend, /END-OF-DAY · ANALYSIS ONLY/, 'historical EOD fallback must be labelled analysis-only');
assert.match(frontend, /STALE · DO NOT TRADE/, 'stale or unknown market data must be visibly blocked from trading');
assert.match(frontend, /DELAYED · ANALYSIS ONLY/, 'delayed market data must be labelled analysis-only');
assert.match(frontend, /UNVERIFIED · ANALYSIS ONLY/, 'unofficial provider quotes must not be labelled LIVE · VERIFIED');
assert.match(frontend, /UNOFFICIAL_YAHOO_SOURCE_ANALYSIS_ONLY/, 'freshness UI must distinguish an unofficial source from a live verified quote');
assert.match(server, /\/api\/market-data-stream/);
assert.match(server, /\/api\/instrument-search/, 'dynamic ticker and issuer resolution endpoint must be registered');
assert.match(server, /query1\.finance\.yahoo\.com\/v1\/finance\/search/, 'instrument lookup must use the live instrument directory');
assert.match(server, /selectPrimaryMarketQuote\(quotes,timestampState\)/, 'market quote selection should prefer a fresh provider timestamp');
assert.match(server, /price:winner\.price/, 'the exposed price must come from the provider named in the response');
assert.match(server, /sourceReady=Boolean\(winner\.live!==false&&winner\.executionEligible!==false&&primaryTimestampValid/, 'the execution safety gate must require provider timestamp provenance and explicit source eligibility');
assert.match(server, /executionEligible:false,executionEligibilityReason:'UNOFFICIAL_YAHOO_SOURCE_ANALYSIS_ONLY'/, 'unofficial Yahoo chart equity data must remain analysis-only even when its timestamp is fresh');
assert.match(server, /quotes\.every\(x=>x\.live!==false&&x\.executionEligible!==false\)/, 'every source contributing to an execution-approved quote must be eligible');
assert.match(server, /UNOFFICIAL_PROVIDER_ANALYSIS_ONLY/, 'the API must explain when an unofficial provider blocks paper execution');
assert.match(server, /report\?\.executionEligibilityReason==='UNOFFICIAL_YAHOO_SOURCE_ANALYSIS_ONLY'\?'UNTRUSTED_SOURCE'/, 'stock report gate status must never say VERIFIED_LIVE for an explicitly untrusted source');
assert.match(server, /snapshot\.quality\.forecastEligible=false/, 'market snapshot forecast eligibility must inherit an upstream source veto');
assert.match(server, /createMarketStreamHub/, 'server should use the shared SSE polling hub');
assert.match(server, /createProviderResponseCache/, 'market routes should share a bounded provider-response cache');
assert.match(server, /PROVIDER_RESPONSE_CACHE\.get\(url/, 'both provider JSON adapters should deduplicate identical URLs');
assert.match(server, /Number\(x\.closeTime\)>0\?new Date\(Number\(x\.closeTime\)\)\.toISOString\(\)/, 'Binance timestamps should be sourced from provider closeTime');
assert.match(server, /sourceTimestampType==='PROVIDER_TIMESTAMP'/, 'crypto market reports should distinguish provider timestamps from observation timestamps');

assert.match(server, /MARKET_STREAM_HUB\.subscribe/, 'each SSE connection should subscribe to a shared channel');
assert.match(frontend, /addEventListener\('open',[\s\S]*?startFallback\(\)/, 'SSE connection open must keep HTTP fallback active until verified market data arrives');
assert.match(frontend, /const live=Boolean\(d\.verified&&d\.status==='LIVE'&&Number\.isFinite\(Number\(d\.price\)\)&&Number\(d\.price\)>0&&d\.asOf/, 'stream data needs a valid provider timestamp before it can stop fallback polling');
assert.match(frontend, /addEventListener\('status',[\s\S]*?startFallback\(\)/, 'server status/error events should activate HTTP fallback');
assert.match(frontend, /sourceTimestampType:'PROVIDER_TIMESTAMP'/, 'verified stream data should carry its provenance into the shared freshness classifier');
assert.doesNotMatch(frontend, /fetch\('\/api\/market-ingest'/, 'browser tabs should not duplicate market tick ingestion');
assert.match(server, /storeMarketTick\(tick\)/, 'the shared server poll should ingest each verified tick once');
assert.match(server, /FINPILOT_MARKET_CACHE_MS\|\|15000/);
assert.match(server, /FINPILOT_YAHOO_COOLDOWN_MS\|\|60000/);


assert.match(server,/fetchTejHqEod\(t,\{allowedSymbols:Object\.keys\(INDIA_EQUITIES\)\}\)/,'Indian equity EOD fallback must be restricted to Indian symbols');
assert.match(server,/LIVE_EQUITY_QUOTE_UNAVAILABLE_EOD_FALLBACK_USED/,'EOD fallback must announce that live quotes were unavailable');
assert.match(server,/PRIMARY_EQUITY_QUOTE_STALE_OR_NON_LIVE/,'stale or non-live primary equity quotes must trigger the EOD fallback path');
assert.match(server,/report\?\.live===false/,'a non-live primary quote must never be accepted as fresh merely because retrieval succeeded');
assert.match(server,/fetchTejHqEod\(raw,\{allowedSymbols:Object\.keys\(INDIA_EQUITIES\)\}\)/,'Market Data OS may expose EOD context only as a fallback');
assert.match(server,/const primaryStale=!liveQuoteOk\|\|!primary\|\|primary\.live===false/,'Market Data OS must treat successful-but-non-live primary quotes as stale');
assert.match(server,/primaryAgeMs>EXECUTION_FRESHNESS_MS/,'Market Data OS must trigger fallback when a primary timestamp is older than the execution freshness threshold');
assert.match(server,/if\(primary\)quotes\.splice\(quoteCountBeforePrimary\)/,'stale primary quote must not outrank the EOD analysis fallback');
assert.match(server,/executionReady=Boolean\(verified&&winner\.live!==false/,'EOD fallback must remain execution-ineligible');
assert.match(server,/TejHQ public EOD/,'EOD source must retain its explicit provider provenance');
assert.match(nasdaqEod,/Nasdaq public historical data · EOD · analysis only/,'keyless Nasdaq EOD source must be explicitly analysis-only');
assert.match(server,/addProvider\('nasdaq-public',async\(\)=>fetchNasdaqEod\(symbol\)\)/,'keyless Nasdaq EOD source must be registered with a stable provider ID');
assert.match(server,/id:'nasdaq-public',configured:true,role:'no-key US equity EOD fallback'/,'provider status must expose the no-key US EOD source');
assert.match(server,/sourceTimestampType:gp\.sourceTimestampType\|\|'HISTORICAL_EOD'/,'global historical fallback must preserve source-date provenance');
assert.match(server,/executionEligibilityReason:gp\.executionEligibilityReason\|\|'HISTORICAL_DATA_ANALYSIS_ONLY'/,'historical fallback must remain execution-ineligible');
assert.match(server,/report\?\.live===false&&Array\.isArray\(report\.candles\)&&report\.candles\.length>=2/,'matching delayed/EOD candles may remain visible for historical context only');
assert.match(server,/LIVE_EQUITY_QUOTE_UNAVAILABLE_HISTORICAL_CHART_USED/,'EOD candles must be labelled historical and remain ineligible');
assert.match(server,/executionEligibilityReason:historicalReport\.executionEligibilityReason\|\|'HISTORICAL_DATA_ANALYSIS_ONLY'/,'historical equity fallback must state its analysis-only execution gate');
assert.doesNotMatch(server,/const SBC_SERVER=/,'a fixed stale SBC price snapshot must not be used as a silent fallback');
assert.match(server,/END_OF_DAY_ANALYSIS_ONLY/,'historical context must not be labelled VERIFIED_LIVE');
assert.match(server,/timeout\|abort\|ECONNRESET/,'timeout failures should cool down the provider and reduce duplicate requests');
assert.match(server,/for\(const p of providers\)\{try\{return await trackedProvider\(p.id,p.run\)/,'provider cooldown/health tracking must use explicit provider IDs');
console.log('Market data stream contract checks passed.');
