import fs from 'node:fs';
import assert from 'node:assert/strict';

const moduleText = fs.readFileSync(new URL('../public/one-click-analysis.js', import.meta.url), 'utf8');
const pageText = fs.readFileSync(new URL('../public/index.html', import.meta.url), 'utf8');
const deepText = fs.readFileSync(new URL('../public/deep-learning-os.js', import.meta.url), 'utf8');
const serverText = fs.readFileSync(new URL('../server/server.mjs', import.meta.url), 'utf8');
const staticStart = serverText.indexOf('function staticFile(');
const staticEnd = serverText.indexOf('\n}', staticStart);
assert.ok(staticStart >= 0 && staticEnd > staticStart, 'static file handler must exist');
const staticHandler = serverText.slice(staticStart, staticEnd);
const launcherStart = pageText.indexOf('async function finpilotLaunch(q){');
const launcherEnd = pageText.indexOf('function exportJSON(', launcherStart);
assert.ok(launcherStart >= 0 && launcherEnd > launcherStart, 'single one-click launcher must exist');
const launcher = pageText.slice(launcherStart, launcherEnd);

assert.match(moduleText, /async function fetchJsonBounded\(/, 'market fetch plus JSON parsing must have a bounded deadline');
assert.match(moduleText, /fpPipelineStatus/, 'pipeline status must be outside the results container');
assert.match(moduleText, /!document\.getElementById\('search'\)\?\.classList\.contains\('active'\)/, 'analysis must not re-render an already-active search view');
assert.match(moduleText, /Analysis stopped safely/, 'a failed analysis must render a visible error');
assert.match(moduleText, /No real order was placed/, 'analysis must remain decision support only');
assert.match(moduleText, /FinPilotDecisionCore\.computeExecutiveDecision\(state,cycle\.findings,web,formatMoney,sourceAge\)/, 'Decision Core must receive the formatter function, never a scenario object');
assert.match(moduleText, /typeof window\.FinPilotBridge\?\.money==='function'/, 'use the global finance formatter when available');
assert.doesNotMatch(moduleText, /computeExecutiveDecision\(state,cycle\.findings,web,preMoney,sourceAge\)/, 'the scenario/formatter argument mismatch must not return');
assert.match(moduleText, /normalizeTicker\(directMarket\.ticker\|\|directMarket\.symbol\)!==normalizeTicker\(candidate\.ticker\)/, 'do not render a quote for a different instrument than the resolved candidate');
assert.match(moduleText, /function marketTrustState\(market\)/, 'market UI must derive its trust badge from timestamp provenance and the execution gate');
assert.match(moduleText, /market\?\.executionEligible===true&&sourceTimestampType==='PROVIDER_TIMESTAMP'/, 'UI must only label a quote VERIFIED LIVE when its provider timestamp and execution gate both pass');
assert.match(moduleText, /FRESH OBSERVATION · UNVERIFIED/, 'observation-only quotes must display an explicit unverified status');
assert.match(moduleText, /realtimeAvailable:trust\.verified/, 'UI real-time availability must follow the verified gate, not the raw live flag');
assert.doesNotMatch(moduleText, /market\.live\?'LIVE DATA':'NON-LIVE DATA'/, 'UI must not label observation-only quote time as live data');
assert.match(deepText, /\['AXISBANK','Axis Bank Limited'\]/, 'Axis Bank must be in the known instrument registry');
assert.match(deepText, /SBI:'SBIN'/, 'SBI alias should resolve to State Bank of India ticker SBIN');
assert.match(deepText, /const normalizePhrase=text=>/, 'instrument matching must use normalized token boundaries');
assert.match(deepText, /hasPhrase\(q,c\[0\]\)/, 'known instrument identity must be anchored to the user query, not incidental headlines');
assert.doesNotMatch(deepText, /hasPhrase\(corpus,c\[0\]\)/, 'search result mentions must never select an unrelated instrument');
assert.doesNotMatch(deepText, /corpus\.includes\(c\[0\]\)/, 'substring-based ticker false positives must not return');
assert.match(moduleText, /\[o,h,l,c\]\.every\(v=>Number\.isFinite\(v\)&&v>0\)/, 'chart analysis must discard zero-price candles');
assert.match(moduleText, /const s20=positive\(market\.sma20\),s50=positive\(market\.sma50\)/, 'null/zero moving averages must remain unavailable');
assert.match(moduleText, /const chartPrice=value=>Number\(value\)>0\?.*:'N\/A'/, 'missing or zero-price chart indicators should render N/A instead of ₹0.00');
assert.match(serverText, /Equity provider returned insufficient valid OHLC candles/, 'server should reject a series after invalid candles are filtered');
assert.match(serverText, /x\.high>=Math\.max\(x\.open,x\.close,x\.low\)/, 'server candles must pass OHLC consistency validation');
assert.match(moduleText, /Resolved market snapshot request/, 'reload market data for the search-resolved instrument when symbols disagree');
assert.doesNotMatch(moduleText, /function mountSearchCard\(/, 'duplicate analysis launcher cards must not be injected');

assert.match(pageText, /async function fpFetchJson\(/, 'search endpoint must bound fetch and JSON parsing');
assert.match(pageText, /window\.__fpSearchSequence/, 'searches need monotonically increasing sequence IDs');
assert.match(pageText, /searchSequence!==window\.__fpSearchSequence/, 'stale search responses must not overwrite newer results');
assert.match(pageText, /markFinpilotSearchDirty\(this\.value\)/, 'editing/clearing the query must invalidate stale results');
assert.match(pageText, /one-click-analysis\.js\?v=20261009-4/, 'rebuilt one-click module must use a new asset version');
assert.doesNotMatch(launcher, /finpilotDirectOneClick\(/, 'launcher must not fall back to a separate, unbounded analysis implementation');
assert.match(launcher, /finally\s*\{\s*restore\(\)/, 'launcher controls must always be restored');

assert.match(moduleText, /Exposure gate:/, 'P/L scenario must distinguish hypothetical outcomes from approved exposure');
assert.match(moduleText, /market\.currency\|\|\(String\(market\.market\|\|''\)\.toUpperCase\(\)==='CRYPTO'\?'USD':'INR'\)/, 'quote display must default to USD for crypto and INR for equities');
assert.match(moduleText, /BINANCE:'\+ticker\.replace\(/, 'crypto chart fallback must use Binance symbol rather than NSE symbol');
assert.match(moduleText, /LATEST MARKET DATA/, 'snapshot card must not label crypto data as equity-only');
assert.match(moduleText, /hypothetical outcomes on the full ₹1,000 example/, 'P/L cards must explain the assumed scenario amount');
assert.match(serverText, /buildMarketSnapshot/, 'server should normalize provider reports into the shared snapshot schema');
assert.match(serverText, /function gateMarketReport\(report,ticker,interval/, 'stock reports and market snapshots must use one canonical execution gate');
assert.match(serverText, /sourceTimestampType==='PROVIDER_TIMESTAMP'/, 'crypto execution eligibility must require a provider-sourced quote timestamp');
assert.match(serverText, /hasProviderTimestamp&&sourceAgeMs<=EXECUTION_FRESHNESS_MS&&sourceRange==='5d\/1h'/, 'equity execution eligibility must require a fresh provider timestamp, not a locally generated timestamp');
assert.match(serverText, /executionDecision:eligible\?'ALLOW_PAPER_ONLY':'HOLD_FOR_VERIFICATION'/, 'market snapshots must expose the same gated paper-eligibility decision');
assert.match(serverText, /status=verified\?'VERIFIED':!priceAgreement\?'CONFLICTING':!primaryTimestampValid\?'UNVERIFIED_TIMESTAMP'/, 'Market Data OS must explain observation-only timestamp failures instead of calling available prices unavailable');
assert.match(serverText, /executionEligible:executionReady,executionDecision:executionReady\?'ALLOW_PAPER_ONLY':'HOLD_FOR_VERIFICATION'/, 'Market Data OS top-level eligibility must match its decision');
assert.match(serverText, /executionEligible:Boolean\(verified&&!stale&&ageMs<=EXECUTION_FRESHNESS_MS&&d\?\.marketDataOS\?\.decision==='ALLOW_ANALYSIS_AND_PAPER'\)/, 'market stream must block stale quotes from execution eligibility even when upstream once approved them');
assert.match(serverText, /function aggregateDataHealthSources\(now=Date\.now\(\)\)/, 'provider health must aggregate adapter aliases into canonical upstream providers');
assert.match(serverText, /const providers=aggregateDataHealthSources\(now\)/, 'health quality score must count canonical providers rather than duplicate adapters');
assert.match(serverText, /providers:providerHealthSnapshot\(\),cooldowns:diagnostics\.providerCooldowns,dataQuality:diagnostics\.dataQuality/, 'market provider health must expose real providers and cooldown diagnostics');
assert.match(serverText, /const moduleCooldown=providerCooldownStatus\(p\.id,now\)/, 'provider cooldown diagnostics must be recalculated at response time');
assert.match(serverText, /cooldownActive:cooldownMs>0/, 'cooldownActive must be derived from the exact remaining cooldown duration');
assert.match(serverText, /cooldownMs,\s*cooldown:moduleCooldown/, 'provider health must return a coherent cooldown timer and state');
assert.match(serverText, /existing\.providerCooldownUntil=Math\.max\(Number\(existing\.providerCooldownUntil\)\|\|0,Number\(p\.cooldownUntil\)\|\|0\)/, 'provider registry cooldown deadlines must survive canonical provider aggregation');
assert.match(serverText, /const report=hit\.report\?gateMarketReport\(hit\.report,t,interval\):null/, 'cached reports must be rechecked for freshness before execution eligibility is returned');
assert.match(serverText, /const baseAsset=key\.replace\(\/USDT\$\/,''\)/, 'crypto provider fallbacks must normalize BTCUSDT-style aliases before building fallback pair names');
assert.match(serverText, /const krakenPair=baseAsset==='BTC'\?'XBTUSD':baseAsset\+'USD'/, 'Kraken fallback must use its XBT symbol for BTC aliases and the canonical base asset for other coins');
assert.match(serverText, /const coinPair=baseAsset\+'-USD'/, 'Coinbase fallback must use a canonical BASE-USD pair rather than appending USD to USDT aliases');
assert.match(serverText, /const name=baseAsset;/, 'crypto reports must expose the canonical base symbol to market snapshot validation');
assert.match(serverText, /provider:'google-search-bridge',results:\[\],externalUrl:google/, 'free search failures should return a usable external Google Search fallback instead of HTTP 502');
assert.match(serverText, /fallback:'GOOGLE_SEARCH_BRIDGE'/, 'the search API must label its Google fallback explicitly');
assert.match(pageText, /d\.fallback==='GOOGLE_SEARCH_BRIDGE'/, 'search UI must show the friendly fallback message');
assert.match(pageText, /Open current results/, 'empty or unavailable web search must retain an external search link');
assert.match(serverText, /u\.pathname==='\/api\/research\/fetch'/, 'a dedicated backend article retrieval route must be registered');
assert.match(serverText, /function isPublicResearchIp/, 'article retrieval must reject private and non-public IP ranges');
assert.match(serverText, /function safeResearchUrl/, 'article retrieval must validate every URL and redirect target');
assert.match(serverText, /u\.protocol!=='https:'/ , 'article retrieval must require HTTPS');
assert.match(serverText, /u\.port&&u\.port!=='443'/, 'article retrieval must refuse non-standard HTTPS ports');
assert.match(serverText, /RESEARCH_FETCH_RATE_LIMIT=60/, 'article retrieval must have a bounded global request budget');
assert.match(serverText, /if\(!researchFetchRateAllowed\(\)\)return send\(res,429/, 'article retrieval rate limits must return a clear retryable response');
assert.match(serverText, /dns\.lookup\(current\.hostname,\{all:true,verbatim:true\}\)/, 'article retrieval must validate DNS answers before connecting');
assert.match(serverText, /RESEARCH_FETCH_MAX_BYTES/, 'article retrieval must enforce a response-size limit');
assert.match(serverText, /Source redirected too many times/, 'article retrieval must cap redirect depth');
assert.match(serverText, /RESEARCH_FETCH_CACHE_TTL_MS/, 'retrieved article pages must use a bounded short cache');
assert.match(pageText, /function retrieveTopSearchPages\(results,searchSequence\)/, 'search must run a bounded top-result retrieval stage');
assert.match(pageText, /\/api\/research\/fetch\?url=/, 'the search UI must use the guarded article retrieval API');
assert.match(pageText, /retrievedText:String\(fetched\.text\)\.slice\(0,15000\)/, 'retrieved text must remain bounded before being passed to analysis');
assert.match(pageText, /ARTICLE RETRIEVED/, 'results must visually distinguish retrieved article pages from search snippets');
assert.match(pageText, /window\.__fpSearchSequence=\(Number\(window\.__fpSearchSequence\)\|\|0\)\+1;/, 'changing the query must invalidate older in-flight search results');
assert.match(pageText, /id="googleEvidencePaste"/, 'search page must expose a mobile-friendly paste field for Google evidence');
assert.match(pageText, /function importGoogleEvidence\(\)/, 'pasted Google research must have a wired import handler');
assert.match(pageText, /provider:'user-provided',provenance:'USER_PROVIDED'/, 'manual import must preserve user-provided provenance');
assert.match(pageText, /User-provided research — not independently verified/, 'manual evidence must be distinguished from fetched evidence');
assert.match(pageText, /Publication date not verified/, 'manual import must not invent publication dates');
assert.match(pageText, /if\(!manual\)state\.lastEvidenceSync=/, 'manual import must not pretend a web source was freshly synchronized');
assert.match(pageText, /async function retryResearchSource\(index\)/, 'unavailable article sources must offer a user-triggered retry');
assert.match(pageText, /data-search-result-index=/, 'search result cards must be addressable for targeted retrieval updates');
assert.match(pageText, /Article retrieval retry/, 'retry must use the safe backend retrieval endpoint rather than browser scraping');
assert.match(pageText, /Publisher still blocks automated retrieval; original snippet retained/, 'failed retries must preserve the original search snippet and explain the limitation');
assert.match(pageText, /retrievalStatus==='RETRIEVED'\?'ARTICLE RETRIEVED'/, 'successful retrieval must update the visible retrieval status');

assert.equal((serverText.match(/u\.pathname==='\/api\/health'/g)||[]).length,1,'health endpoint must have exactly one reachable route');
assert.match(serverText, /dataQualityScore:diagnostics\.dataQualityScore/, 'health endpoint must expose the derived data-quality score separately from service availability');
assert.match(serverText, /'X-FinPilot-Version':'8\.6'/, 'API version header must match the health endpoint version');
assert.match(serverText, /status:'OPERATIONAL'/, 'health endpoint must report API availability separately from data readiness');
assert.match(serverText, /function dataHealthDiagnostics\(\)/, 'health response must calculate detailed provider readiness diagnostics');
assert.match(serverText, /lastSuccessAgeMs/, 'health response must show provider success age to detect stale data');
assert.match(serverText, /dataQualityWarnings:diagnostics\.warnings/, 'health response must explain why data quality is unknown or degraded');
assert.match(serverText, /dataSources:diagnostics\.sources/, 'health response must expose provider-by-provider status without credentials');
assert.match(serverText, /readiness:diagnostics\.dataQuality===['"]FRESH['"]\?['"]MARKET_DATA_READY['"]/, 'market data readiness must be distinct from API availability');
assert.match(serverText, /ai:\{configured:aiConfigured,mode:aiConfigured\?['"]EXTERNAL_GATEWAY['"]:['"]DETERMINISTIC_ONLY['"]\}/, 'unconfigured external AI must be reported accurately');
assert.match(serverText, /paidFallbackEnabled:paidSearchFallbackEnabled/, 'health response must disclose whether paid fallback is enabled');
assert.match(serverText, /providerCooldownStatus,recordProviderFailure,recordProviderSuccess/, 'market providers must use a shared cooldown state for rate-limit recovery');
assert.match(serverText, /const cooldownError=providerCooldownError\(source\);if\(cooldownError\)return Promise\.reject\(cooldownError\)/, 'a cooling-down provider must be skipped before issuing another outbound request');
assert.match(serverText, /recordProviderFailure\(source,e\.message\)/, 'rate-limit and block responses must start a provider-specific cooldown');
assert.match(serverText, /recordProviderSuccess\(source\)/, 'successful provider responses must clear prior cooldown state');
assert.match(serverText, /activeProviderCooldowns\(now\)/, 'health diagnostics must include active provider cooldowns');
assert.match(serverText, /providerCooldowns:diagnostics\.providerCooldowns/, 'health endpoint must expose cooldown state for operators');
assert.match(serverText, /cooling down for about .*seconds after/, 'health warnings must explain when a provider is being temporarily skipped');
assert.match(serverText, /const forceRefresh=u\.searchParams\.get\(['"]refresh['"]\)===['"]1['"]/, 'search endpoint must accept an explicit fresh-search request');
assert.match(serverText, /searchWeb\(q,\{count,forceRefresh\}\)/, 'fresh-search requests must bypass the provider cache');
assert.match(pageText, /function refreshCurrentSearch\(\)/, 'search UI must provide a refresh action');
assert.match(pageText, /doSearch\(q,true\)/, 'refresh action must request a forced new search');
assert.match(pageText, /\(forceRefresh\?'&refresh=1':''\)/, 'regular searches must retain cache while explicit refreshes bypass it');
assert.match(serverText, /version:'8[.]6'/, 'health endpoint must expose the expected service version');
assert.match(serverText, /X-FinPilot-Version':'8[.]6'/, 'API version header must match the health endpoint version');
assert.match(serverText, /res\.setHeader\('X-FinPilot-Version','8[.]6'\)/, 'default API response header must match the service version');
assert.match(serverText, /'X-FinPilot-Version':'8[.]6'/, 'market event stream must expose the service version');
assert.match(serverText, /dataQuality:diagnostics\.dataQuality,dataQualityScore:diagnostics\.dataQualityScore/, 'health endpoint must expose derived data quality and its score');
assert.match(serverText, /primaryTimestampValid=winner\.timestampType==='PROVIDER_TIMESTAMP'/, 'market data must require the selected primary quote to carry a provider-supplied timestamp');
assert.match(serverText, /const sourceValue=x\.asOf\|\|x\.observedAt\|\|null/, 'provider time and local observation time must be kept explicitly typed');
assert.match(serverText, /const valid=Number\.isFinite\(ts\)&&ts<=now\+5000/, 'invalid or future quote timestamps must be rejected');
assert.match(serverText, /sourceTimestampType:selectedTimestampType/, 'Market Data OS must expose whether the selected timestamp is provider-sourced or observation-only');
assert.match(serverText, /u\.pathname==='\/api\/market-snapshot'/, 'the market snapshot endpoint must be registered');
assert.match(moduleText, /\/api\/market-snapshot/, 'one-click analysis must consume the canonical snapshot endpoint');
assert.match(moduleText, /window\.__fpMarketSnapshot=marketSnapshot/, 'one-click must expose one shared snapshot to the agent fleet');
assert.match(moduleText, /runFleet\(state,\{web,candidate,marketSnapshot:window\.__fpMarketSnapshot\}\)/, 'the agent fleet must receive the same validated snapshot');
assert.match(moduleText, /state\.forecastLedger\.unshift\(forecastRecord\)/, 'completed runs must append a forecast ledger record');
assert.match(moduleText, /BLOCKED_UNVERIFIED_DATA/, 'unverified market data must be explicitly blocked in the forecast ledger');
assert.match(staticHandler, /script-src[^;]*https:\/\/s3\.tradingview\.com/, 'static page CSP must permit the TradingView chart loader');
assert.match(staticHandler, /frame-src[^;]*https:\/\/www\.tradingview\.com/, 'static page CSP must permit the TradingView chart iframe');
assert.match(moduleText, /if\(validCandles\.length<2\)/, 'local historical candles should render even when the quote is not live');
assert.match(moduleText, /Historical \/ delayed price series/, 'non-live candle charts must be labelled historical/delayed');
assert.match(moduleText, /Latest reported price · non-live\/EOD/, 'EOD or delayed quotes must not be labelled verified live prices');
assert.match(moduleText, /script\.onerror=\(\)=>showFallback/, 'failed external chart loads must produce a visible fallback instead of a blank box');
assert.match(moduleText, /marketForecastEligible===true&&scenarioQuoteValid/, 'the verified live price label must require both snapshot eligibility and a fresh matching quote');
assert.match(deepText, /marketDataQuality/, 'agents must score market data quality as a separate feature');
assert.match(deepText, /marketSnapshotId:marketSnapshot\?\.snapshotId/, 'agent results must preserve the shared snapshot ID');


assert.match(moduleText, /\/api\/market-data-os\?ticker=/, 'ineligible snapshots must trigger an independent quote verification attempt');
assert.match(moduleText, /quoteVerified=Boolean\(os\?\.verified===true&&os\?\.executionEligible===true/, 'predictions may use only independently verified quotes');
assert.match(moduleText, /PROVIDER_TIMESTAMP/, 'risk scenario must require provider-sourced quote time');
assert.match(moduleText, /INDEPENDENT_PROVIDER_VERIFIED/, 'the quote provenance should be explicit in the analysis trace');


assert.match(moduleText, /\/api\/instrument-search\?q=/, 'unlisted company names and tickers should use live instrument-directory lookup');
assert.match(moduleText, /function isBroadMarketRequest\(query\)/, 'only entity-free discovery requests may fall back to market picks');
assert.match(moduleText, /No unambiguous instrument match was found/, 'unresolved entity requests must not silently substitute an unrelated stock');

console.log('one-click-pipeline: contract checks passed');
