import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../public/tradingview-paper-bridge.js',import.meta.url),'utf8');
const window={};const document={readyState:'loading',addEventListener(){}};
vm.runInNewContext(source,{window,document,MutationObserver:function(){},setInterval,clearInterval,Event,console});
const api=window.FinPilotTradingViewBridge;
assert.equal(api.normalizeSymbol(' btcusdt '),'BTCUSDT');
assert.equal(api.normalizeSymbol('BTC USDT'),'BTCUSDT');
assert.equal(api.normalizeSymbol('javascript:alert(1)'),'');
assert.equal(api.tvSymbol('BTCUSDT','AUTO'),'BINANCE:BTCUSDT');
assert.equal(api.tvSymbol('BTC','CRYPTO'),'BINANCE:BTCUSDT');
assert.equal(api.tvSymbol('RELIANCE.NS','AUTO'),'NSE:RELIANCE');
assert.equal(api.tvSymbol('RELIANCE','INDIA'),'NSE:RELIANCE');
assert.equal(api.tvSymbol('AAPL','US'),'NASDAQ:AAPL');
assert.equal(api.tvSymbol('NASDAQ:MSFT','AUTO'),'NASDAQ:MSFT');
assert.match(api.widgetUrl('AAPL'),/symbol=NASDAQ%3AAAPL/);
assert.equal(api.widgetUrl(''), '');
assert.equal(api.paperSymbol('NASDAQ:AAPL'),'AAPL');
assert.equal(api.paperSymbol('NSE:RELIANCE'),'RELIANCE');
assert.equal(api.paperSymbol('BINANCE:BTCUSDT'),'BTCUSDT');
assert.equal(api.paperSymbol('javascript:alert(1)'),'');
console.log('tradingview-paper-bridge: 15 assertions passed');
