import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../public/upgrade-v8.js',import.meta.url),'utf8');
const context={}; vm.runInNewContext(source.replace('window.FinPilotV8={version:','globalThis.__v8={version:'),context);
const e=context.__v8;
assert.equal(e.upgradeCount,50);
assert.equal(e.upgrades.length,50);
assert.equal(new Set(e.upgrades).size,50);
const report={risk:42,confidence:74,quantumSignal:{confidence:82,evidenceCount:6,freshness:'FRESH'},webSignal:{count:6,stance:'Positive'},evidenceFreshness:'FRESH',executive:{ceoConfidence:78,cfoConfidence:71,judgeConfidence:74,inputs:{disagreement:7,evidence:80,liquidity:75,debt:82,market:68}}};
const money={amount:1000,action:'BUY BIAS',buyProbability:66,sellProbability:18,holdProbability:16,upsidePct:8,downsidePct:5,riskReward:1.6,expectedValue:35};
const x=e.analyze(report,money,{amount:1000});
assert.equal(x.version,'8.0.0');
assert.equal(x.upgradeCount,50);
assert.ok(x.position.maximumSafe>=0);
assert.ok(x.position.maximumSafe<=1000);
assert.ok(x.riskMetrics.riskReward>0);
assert.ok(x.scenarios.stress90>=x.scenarios.stress30);
assert.ok(x.auditId.startsWith('FP8-'));
console.log('FinPilot v8: 50/50 upgrades loaded and scenario guards passed');
console.log('Gate:',x.gate,'safe position:',x.position.recommended);
